spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/ejemploangular
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- Configuraci�n de JPA / Hibernate ---
# Habilita la creaci�n/actualizaci�n de tablas autom�tica (update, create, none)
spring.jpa.hibernate.ddl-auto=update
# Muestra las consultas SQL en la consola
spring.jpa.show-sql=true

# --- Configuraci�n del Servidor ---
server.port=8080
